##Importar la libreria

In [ ]:
import numpy as np

Crear arrays a partir de una lista

In [ ]:
lista = [1,2,3,4,5]
print(lista)
array = np.array(lista)
print(array)
array.shape

[1, 2, 3, 4, 5]
[1 2 3 4 5]


(5,)

In [ ]:
# Array con rango de valores:
array = np.arange(start=0, stop=101, step=5)
print(array)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]


In [ ]:
array = np.arange(0, 101, 5)
print (array)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]


In [ ]:
array.shape

(21,)

In [ ]:
array = np.linspace(start=0, stop=100, num=101)
print(array)

[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.
  14.  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.
  28.  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.
  42.  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.
  56.  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.
  70.  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.
  84.  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.
  98.  99. 100.]


Crear arrays de Zeros

In [ ]:
array = np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# Array lleno de ceros o unos:
# Python
zeros = np.zeros((2, 3))  # Matriz 2x3 de ceros
print(zeros)


[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
ones = np.ones((3, 2))   # Matriz 3x2 de unos
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
# Array con valores aleatorios:
# Python
array = np.random.rand(3, 3)  # Matriz 3x3 con valores aleatorios entre 0 y 1
print(array)

[[0.14490076 0.43504087 0.15855803]
 [0.93591342 0.31791078 0.27880572]
 [0.77404663 0.38725433 0.46980788]]


In [ ]:
# Tipo de datos:
array.dtype  # Devuelve el tipo de datos (e.g., int32, float64)

dtype('float64')

In [ ]:
# 3. Propiedades del Array

# Forma del array:
array.shape  # Devuelve (filas, columnas)

(3, 3)

In [ ]:
array = np.full(shape=(1), fill_value=1)
print(array)

[1]


In [ ]:
array = np.full(shape=(1, 1), fill_value=1)
print(array)

[[1]]


In [ ]:
array = np.full(shape=(1, 2), fill_value=2)
print(array)

[[2 2]]


In [ ]:
array = np.full(shape=(2, 1), fill_value=2)
print(array)

[[2]
 [2]]


In [ ]:
array = np.full(shape=(1, 3), fill_value=3)
print(array)

[[3 3 3]]


In [ ]:
array = np.full(shape=(3, 1), fill_value=3)
print(array)

[[3]
 [3]
 [3]]


In [ ]:
array = np.full(shape=(2, 3), fill_value=3)
print(array)

[[3 3 3]
 [3 3 3]]


In [ ]:
array = np.full(shape=(3, 3), fill_value=3)
print(array)

[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [ ]:
array = np.full(shape=(1, 4), fill_value=4)
print(array)

[[4 4 4 4]]


In [ ]:
array = np.full(shape=(4, 1), fill_value=4)
print(array)

[[4]
 [4]
 [4]
 [4]]


In [ ]:
array = np.full(shape=(4, 5), fill_value=5)
print(array)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [ ]:
array = np.full(shape=(5, 6), fill_value=6)
print(array)

[[6 6 6 6 6 6]
 [6 6 6 6 6 6]
 [6 6 6 6 6 6]
 [6 6 6 6 6 6]
 [6 6 6 6 6 6]]


In [ ]:
array = np.full(shape=(4, 3), fill_value=2)
print(array)

[[2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]]


In [ ]:
array = np.full(shape=(4, 4), fill_value=4)
print(array)

[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]


In [ ]:
array = np.full(shape=(1, 1, 1), fill_value=7)
print(array)

[[[7]]]


In [ ]:
array = np.full(shape=(3, 3, 3), fill_value=1)
print(array)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [ ]:
# Tipo de datos:
array.dtype  # Devuelve el tipo de datos (e.g., int32, float64)

dtype('int64')

# Operaciones Matemáticas

In [ ]:
# 4. Operaciones Matemáticas

lista = [1, 3, 5, 7]
array = np.array(lista)
print(array)

# Suma, resta, multiplicación, división:
suma = array + 2
print(suma)
resta = array - 1
print(resta)
multiplicacion = array * 3
print(multiplicacion)
division = array / 2
print(division)

[1 3 5 7]
[3 5 7 9]
[0 2 4 6]
[ 3  9 15 21]
[0.5 1.5 2.5 3.5]


In [ ]:
#Operaciones entre arrays:
lista1 = [1, 3, 5, 7]
lista2 = [2, 4, 6, 8]
array1 = np.array(lista1)
array2 = np.array(lista2)

resultado = array1 + array2  # Suma elemento a elemento
print(resultado)

[ 3  7 11 15]


# Funciones matemáticas:

In [ ]:
# Funciones matemáticas:
lista3 = [100]
array = np.array(lista3)
print(array)

np.sin(array)  # Seno

[100]


array([-0.50636564])

In [ ]:
np.log(array)  # Logaritmo

array([4.60517019])

In [ ]:
np.sqrt(array) # Raíz cuadrada

array([10.])

# Indexación y Slicing

In [ ]:
# 5. Indexación y Slicing

array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Acceder a elementos:
elemento = array[1, 2]  # Elemento en la fila 1, columna 2
print(elemento)

6


In [ ]:
# Cortar arrays:
subarray = array[0:2, 1:3]  # Subarray de filas 0-1 y columnas 1-2
print(subarray)

[[2 3]
 [5 6]]


# Manipulación de Arrays

In [ ]:
# 6. Manipulación de Arrays

array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#Cambiar forma:
reshaped = array.reshape(3, 3)  # Cambia a una matriz 3x3
print(reshaped)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Define array1 and array2 before concatenation
array1 = np.array([[1, 2, 3]])
array2 = np.array([[4, 5, 6]])
print(array1)
print(array2)


[[1 2 3]]
[[4 5 6]]


In [ ]:
# Concatenar arrays:
concatenado = np.concatenate((array1, array2), axis=0)  # Concatenar filas
print(concatenado)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 7. Estadísticas
# Operaciones comunes:
np.mean(array)  # Promedio

np.float64(5.0)

In [ ]:
np.sum(array)   # Suma total

np.int64(45)

In [ ]:
np.max(array)   # Máximo

np.int64(9)

In [ ]:
np.min(array)   # Mínimo

np.int64(1)

In [ ]:
np.std(array)   # Desviación estándar

np.float64(2.581988897471611)